export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const TOGGLE_IS_DONE = 'TOGGLE_IS_DONE';
export const TOGGLE_IS_IMPORTANT = 'TOGGLE_IS_IMPORTANT';
export const TOGGLE_IS_DONE = 'TOGGLE_IS_DONE';

export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
